spring:
  datasource:
    url: ${URL:jdbc:postgresql://localhost:5432/AgreementRegistration}
    username: ${USERNAME:postgres}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  freemarker:
    template-loader-path: "classpath:/templates"
    suffix: ".ftl"

security-user:
  name: ${ADMIN_USERNAME:admin}
  password: ${ADMIN_PASSWORD:admin}