spring:
  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  freemarker:
    template-loader-path: "classpath:/templates"
    suffix: ".ftl"
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

security-user:
  name: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}

baseUrl: ${BASE_URL}
