spring:
  datasource:
    url: ${URL:jdbc:postgresql://localhost:5432/AgreementRegistration}
    username: ${USERNAME:postgres}
    password: ${PASSWORD}
  freemarker:
    template-loader-path: "classpath:/templates"
    suffix: ".ftl"
  servlet:
    multipart:
      max-file-size: 200KB
      max-request-size: 200KB

security-user:
  name: ${ADMIN_USERNAME:admin}
  password: ${ADMIN_PASSWORD:admin}

baseUrl: ${BASE_URL:http://localhost:8080}