server:
  port: ${PORT:8080}
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  freemarker:
    template-loader-path: "classpath:/templates"
    suffix: ".ftl"
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

security-user:
  name: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}

baseUrl: ${APP_URL}

path:
  folder: ${FILES_FOLDER:agreement-registration-app/src/main/resources/agreement_files}
